# Generated by Django 5.0.7 on 2024-07-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0003_user_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
